name: flow-pilot-action
description: flow-pilot-action
author: TDesign
inputs:
  token:
    description: personal access token
  packages:
    description: packages
  pr_number:
    description: pr id
  translate-secret-id:
    description: translate secret id
    required: false
  translate-secret-key:
    description: translate secret key
    required: false

outputs:
  changelog:
    description: changelog
runs:
  using: node20
  main: dist/index.mjs
