import { defineConfig } from 'tsdown'
import packageJson from './package.json' with { type: 'json' }

export default defineConfig({
  platform: 'node',
  shims: true,
  entry: ['src/index.ts'],
  noExternal: [...Object.keys(packageJson.dependencies)],
  inlineOnly: [
    '@actions/core',
    '@actions/http-client',
    'tunnel',
    'undici',
    '@actions/io',
    '@actions/exec',
    '@actions/github',
    '@fastify/busboy',
    'universal-user-agent',
    'before-after-hook',
    '@octokit/endpoint',
    'deprecation',
    'wrappy',
    'once',
    '@octokit/request-error',
    '@octokit/request',
    '@octokit/graphql',
    '@octokit/auth-token',
    '@octokit/core',
    '@octokit/plugin-rest-endpoint-methods',
    '@octokit/plugin-paginate-rest',
    '@isaacs/balanced-match',
    '@isaacs/brace-expansion',
    'minimatch',
    'lru-cache',
    'minipass',
    'path-scurry',
    'glob',
    'fdir',
    'picomatch',
    'tinyglobby',
    'js-yaml',
    'jju',
    '@manypkg/tools',
    '@manypkg/find-root',
    '@manypkg/get-packages',
    'camelcase',
    'marked',
    'tslib',
    'tencentcloud-sdk-nodejs-hunyuan',
    'tencentcloud-sdk-nodejs-common',
    'bignumber.js',
    'json-bigint',
    'is-stream',
    'get-stream',
    'delayed-stream',
    'combined-stream',
    'mime-db',
    'mime-types',
    'asynckit',
    'es-object-atoms',
    'es-errors',
    'math-intrinsics',
    'gopd',
    'es-define-property',
    'has-symbols',
    'get-proto',
    'function-bind',
    'call-bind-apply-helpers',
    'dunder-proto',
    'hasown',
    'get-intrinsic',
    'has-tostringtag',
    'es-set-tostringtag',
    'form-data',
    'webidl-conversions',
    'whatwg-url',
    'tr46',
    'node-fetch',
    'ms',
    'debug',
    'has-flag',
    'supports-color',
    'agent-base',
    'https-proxy-agent',
    'uuid',
  ],
})
